fix mount scripts

diff --git a/scripts/mount_riri b/scripts/mount_riri
--- a/scripts/mount_riri
+++ b/scripts/mount_riri
@@ -4,8 +4,15 @@ set -e
 
 device_name=$(lsblk -l -o NAME,LABEL | grep '\sriri' | cut -f1 -d' ')
 
+if [ -z "${device_name}" ]; then
+    echo "Error: no device found"
+    exit 1
+fi
+
 if [ ! -e /dev/mapper/riri ]; then
     sudo cryptsetup open /dev/${device_name} riri
 fi
 
-sudo mount /dev/mapper/riri ~/mount/riri
+if ! mount | grep /dev/mapper/riri &>/dev/null; then
+    sudo mount --mkdir /dev/mapper/riri ~/mount/riri
+fi
